### ISSUE TITLE
Buttons and screensize

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#41]
You can find a video with the bugs at [youtube video ](https://youtu.be/EWYfhcYCB5c)

The main issues are: 

1. The display size does not adapt the screen size right 
2. The buttons change their size with the change of the x- and y-size 
3. If you change the font size the whole programm becomes pixelated
3. Automatisch not automagisch 
4. If you open the "Erstellte Lernsatz" Window you have no option to close it

Used on Debian GNU/Linux 12 (bookworm)
Version: commit 6645bba5c9069d0ac80439ca67fa6fcfaaa97782

**Comment by NP199** [comment]
1. In working #38 
2. I think this was the idea behind the x and y button. Maybe there should be other labels
3. The font is loaded into the program in the build process. So thy are fixed in their size. Maybe some high resolution font could be a solution for this.
5. There is an button but i think you cant see it because if issue #38

**Comment by AKMaily** [comment]
This issue will be seperated into different issues. 1. The screensize does now adapt to the screensize as everything is a percentage of the screen and not fixed. 2. The buttonsize option in the settings will be deleted as it is now not necessary anymore #143 3. Changing the Fontsize has been set as an issue in #133 4. will be deleted #143 5. The "Create Learning Set Window" has been removed and replaced with the "Generate Training Data" window.
